Why do we need to use pandas
 - numpy is used for performing  numerical operations hence  it is called as numerical python
 - pandas there was need to perform data manipulation
 - pandas stands for panel data to track multiple subjects over time
 - numpy cannot get data from csv files , excel files , pandas can do that 
 - pandas has two main data structure  series and dataframe are the two main data structures in python
 - one dimensional labelled array ,similar to a single column in a table
 - data frame is two dimensional labelled structure  with rows and columns similar to  an excel spreedsheet or sql table

In [2]:
import pandas  as pd
### creating a series data structure in pandas from list
country = ['India','Pakistan','New Zealand']
pd.Series(country)
### creating our custom index
## subjects=['math','science','algebra','trigonometry'] if we have more indexes than the original array we get an error 
### pd.Series(country,index=subjects)
###setting a name 
pd.Series(country,name="jeevan ka result")
### series from a dictionary
dict1={10:'20',30:'50'}
result = pd.Series(dict1)### key becomes index , value becomes the series
#### series attributes
result.size
result.dtype
result.is_unique
result.index###returns the label 
### reading a csv , a csv is a 2d table

Index([10, 30], dtype='int64')

data frame 
- data = facts or information 
- frame = a structure or framework that holds or organizes something 
-  it can also be said that it is a container that contains multiple series labelled data

In [ ]:
####  dataframe is 2d we need to convert it in 1d so we use squeeze
###subs=pd.read_csv('../Dataset/kohli_ipl.csv',squeeze=True) in pandas2.0 was removed
subs = pd.read_csv('../Dataset/kohli_ipl.csv')# with 2 cols
vk = pd.read_csv(
    '../Dataset/kohli_ipl.csv',
    index_col='match_no'
).squeeze('columns')
### index_columns is the label identifier for each row we still need to squeeze it to make it a series
print(type(vk))
###now index_col will become the label 
subs

### series method
vk.tail()
vk.head()
vk.value_counts()

vk
print(type(vk))
### series has the unique behaviour where in we can do positional access as well
# slicing
vk[2:8] = [100,100,100,100,100,100]
print(vk)
vk[-1:]##reverse order positional slice
##other useful operations on series
'''
# len/type/dir/sorted/max/min
print(len(vk))
print(type(vk))
print(dir(vk))
print(sorted(vk))
print(min(vk))
print(max(vk))
'''

<class 'pandas.Series'>
<class 'pandas.Series'>
match_no
1        1
2       23
3      100
4      100
5      100
      ...
211      0
212     20
213     73
214     25
215      7
Name: runs, Length: 215, dtype: int64

match_no
215    7
Name: runs, dtype: int64

some few more operations on series 
 astype
 between
 clip
drop_duplicates
 isnull
 dropna
 fillna
 isin
 apply
 copy

In [ ]:
### creating a dataframe
student_data =[[100,90,80],[100,90,80],[100,90,80]]
# using lists we need to mention the column name in parameter\
pd.DataFrame(student_data,columns=['iq','marks','package'])
##using dict
student_data2={
    'name':['nitish','ankit'],'iq':[1090,100]
}
pd.DataFrame(student_data2)

### reading a csv file the most important thing
result3= pd.read_csv('../Dataset/kohli_ipl.csv')
### loading from url
pd.read_csv('https://raw.githubusercontent.com/mwaskom/seaborn-data/master/iris.csv')
### shape
result3.shape
result3.dtypes
result3.index ### this is the label 
result3.columns
result3.head(7)
result3.tail(7)
result3.info()
result3.describe()
result3.duplicated().sum()
result3.sample(n=6,random_state=None)

<class 'pandas.DataFrame'>
RangeIndex: 215 entries, 0 to 214
Data columns (total 2 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   match_no  215 non-null    int64
 1   runs      215 non-null    int64
dtypes: int64(2)
memory usage: 3.5 KB

     match_no  runs
104       105    35
205       206     0
37         38     9
142       143    21
139       140     5
24         25     7

In Pandas, loc and iloc are used to select rows and columns from a DataFrame or Series. The main difference is:
- loc → label-based indexing.
- iloc → integer position-based indexing.

In [24]:
result3=pd.read_csv('https://raw.githubusercontent.com/mwaskom/seaborn-data/master/iris.csv')
result3.info()
result3.describe()
print(result3.head())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 150 entries, 0 to 149
Data columns (total 5 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   sepal_length  150 non-null    float64
 1   sepal_width   150 non-null    float64
 2   petal_length  150 non-null    float64
 3   petal_width   150 non-null    float64
 4   species       150 non-null    object
dtypes: float64(4), object(1)
memory usage: 6.0+ KB
   sepal_length  sepal_width  petal_length  petal_width species
0           5.1          3.5           1.4          0.2  setosa
1           4.9          3.0           1.4          0.2  setosa
2           4.7          3.2           1.3          0.2  setosa
3           4.6          3.1           1.5          0.2  setosa
4           5.0          3.6           1.4          0.2  setosa

In [8]:
import numpy as np
#### feature cleaning 
### here we are going to clean the data and remove the null values and duplicates
result4=pd.read_csv('https://raw.githubusercontent.com/mwaskom/seaborn-data/master/iris.csv')
result4.isnull().sum()### to check the null values in each column aggregation
result4.dropna()### drop the null values
result4.loc[0,'sepal_length']=np.nan### to access a particular value in the dataframe, this modifiy the original data set
##print(result4)
result4.isnull().sum()### to check the null values in each column aggregation
print(result4.duplicated())### to check the duplicates in the dataframe ,  we check for duplicates in the entire row, if we want to check for a particular column we can use subset parameter
print(result4.rename(columns={'species':'flower_type'},inplace=False))### the original column name is species and it is not changed in the original data set only a copy is created
result4.head()### to rename the column name

0      False
1      False
2      False
3      False
4      False
       ...
145    False
146    False
147    False
148    False
149    False
Length: 150, dtype: bool
     sepal_length  sepal_width  petal_length  petal_width flower_type
0             NaN          3.5           1.4          0.2      setosa
1             4.9          3.0           1.4          0.2      setosa
2             4.7          3.2           1.3          0.2      setosa
3             4.6          3.1           1.5          0.2      setosa
4             5.0          3.6           1.4          0.2      setosa
..            ...          ...           ...          ...         ...
145           6.7          3.0           5.2          2.3   virginica
146           6.3          2.5           5.0          1.9   virginica
147           6.5          3.0           5.2          2.0   virginica
148           6.2          3.4           5.4          2.3   virginica
149           5.9          3.0           5.1          1.8   virginica

[150 rows x 5 columns]

   sepal_length  sepal_width  petal_length  petal_width species
0           NaN          3.5           1.4          0.2  setosa
1           4.9          3.0           1.4          0.2  setosa
2           4.7          3.2           1.3          0.2  setosa
3           4.6          3.1           1.5          0.2  setosa
4           5.0          3.6           1.4          0.2  setosa

In [ ]:
result4.loc[1,'sepal_length']=None
result4
## in pyhtong null is represented by None

     sepal_length  sepal_width  petal_length  petal_width    species
0             NaN          3.5           1.4          0.2     setosa
1             NaN          3.0           1.4          0.2     setosa
2             4.7          3.2           1.3          0.2     setosa
3             4.6          3.1           1.5          0.2     setosa
4             5.0          3.6           1.4          0.2     setosa
..            ...          ...           ...          ...        ...
145           6.7          3.0           5.2          2.3  virginica
146           6.3          2.5           5.0          1.9  virginica
147           6.5          3.0           5.2          2.0  virginica
148           6.2          3.4           5.4          2.3  virginica
149           5.9          3.0           5.1          1.8  virginica

[150 rows x 5 columns]

In [9]:
### masking and filtering
mask = result4['sepal_length']>5.0### check the column sepal_length and return a boolean series where the value is greater than 5.0
mask ### this is series and has only one column and the index is the same as the original data set
### selecting multiple 
result4[['sepal_length','sepal_width']]
result4[result4['sepal_length']>5.0]### this will return the entire row where the condition is true
### result4['sepal_length']>5.0 this retunrns a boolean series where the value is true or false based on the condition
####result4[] returns a row or column depending on what we put in the square brackets, if we put a column name it will return a column and if we put a boolean series it will return a row
result4['sepal_length'] ### this gives the column
result4[mask]### this gives the row where the condition is true

     sepal_length  sepal_width  petal_length  petal_width    species
5             5.4          3.9           1.7          0.4     setosa
10            5.4          3.7           1.5          0.2     setosa
14            5.8          4.0           1.2          0.2     setosa
15            5.7          4.4           1.5          0.4     setosa
16            5.4          3.9           1.3          0.4     setosa
..            ...          ...           ...          ...        ...
145           6.7          3.0           5.2          2.3  virginica
146           6.3          2.5           5.0          1.9  virginica
147           6.5          3.0           5.2          2.0  virginica
148           6.2          3.4           5.4          2.3  virginica
149           5.9          3.0           5.1          1.8  virginica

[117 rows x 5 columns]

In [52]:
## axis in dataframe axis=0 is row and axis=1 is column, in series axis=0 is the only axis
result5=result4.drop(['species'],axis=1)### this will drop the column species and return a new dataframe without the column species
### drop does not drop columns in place
result5.sum(axis=1)
##dropping a specific row
result5.drop(index=0,axis=0)### this will drop the row with

     sepal_length  sepal_width  petal_length  petal_width
1             NaN          3.0           1.4          0.2
2             4.7          3.2           1.3          0.2
3             4.6          3.1           1.5          0.2
4             5.0          3.6           1.4          0.2
5             5.4          3.9           1.7          0.4
..            ...          ...           ...          ...
145           6.7          3.0           5.2          2.3
146           6.3          2.5           5.0          1.9
147           6.5          3.0           5.2          2.0
148           6.2          3.4           5.4          2.3
149           5.9          3.0           5.1          1.8

[149 rows x 4 columns]

In [4]:
### pivot tables
### long format : Each row represents one observation, and different categories are stored as values in a column.
### wide format : Each category becomes its own column.
### meaning we have city [toronto , etobicoke] columns has differnt products sold in tha city so this is differnet categories in each row
### now we want  column of each  product category in each city 
## to pivot is to rotate around an axis like an hinge
## so we pivoted the category row to column and  made the city column as labels or rows
df = pd.DataFrame({
    'City': ['Toronto', 'Toronto', 'Brampton', 'Brampton'],
    'Product': ['Laptop', 'Phone', 'Laptop', 'Phone'],
    'Sales': [1000, 500, 1200, 700]

})
df

       City Product  Sales
0   Toronto  Laptop   1000
1   Toronto   Phone    500
2  Brampton  Laptop   1200
3  Brampton   Phone    700

In [6]:
#### laptop categores should become column
df.pivot(index='City',columns='Product',values='Sales')

Product   Laptop  Phone
City
Brampton    1200    700
Toronto     1000    500

In [40]:
result4.value_counts()### this will return the count of each unique value in the series
### seperates out each column and then returns the count of each unique value in the column 

result4.sort_values(by=['sepal_width'],ascending=True)
result4.isnull()
result4.notnull()
####result4.hasnans() works on series
result4.drop_duplicates()### this will drop the duplicate rows and return a new dataframe without the duplicate rows
result4.fillna(0)### this will fill the null values with 0 and return a new dataframe without the null values
result4.rank()## works on both sereis and dataframe
##result4.unique()### works only on series
print(result4.drop(axis=1, columns=['species']).corr())### this will return the correlation matrix of the dataframe
result4.isin([5.1,3.5])### this will return a boolean dataframe where the value is true if the value is in the list and false if the value is not in the list
result4.sort_index(ascending=False)### this will sort the dataframe by index

              sepal_length  sepal_width  petal_length  petal_width
sepal_length      1.000000    -0.112106      0.871281     0.816961
sepal_width      -0.112106     1.000000     -0.428440    -0.366126
petal_length      0.871281    -0.428440      1.000000     0.962865
petal_width       0.816961    -0.366126      0.962865     1.000000

     sepal_length  sepal_width  petal_length  petal_width    species
149           5.9          3.0           5.1          1.8  virginica
148           6.2          3.4           5.4          2.3  virginica
147           6.5          3.0           5.2          2.0  virginica
146           6.3          2.5           5.0          1.9  virginica
145           6.7          3.0           5.2          2.3  virginica
..            ...          ...           ...          ...        ...
4             5.0          3.6           1.4          0.2     setosa
3             4.6          3.1           1.5          0.2     setosa
2             4.7          3.2           1.3          0.2     setosa
1             4.9          3.0           1.4          0.2     setosa
0             NaN          3.5           1.4          0.2     setosa

[150 rows x 5 columns]

In [ ]:
##### grouping and aggregation

In [22]:
import pandas as pd
imdb=pd.read_csv('../Dataset/imdb-top-1000.csv')
delevires=pd.read_csv('../Dataset/deliveries.csv')
imdb.head()
delevires.head()
### grouping by generes
return_value =imdb.groupby('Genre').mean(numeric_only=True)
print(imdb.groupby('Genre').groups)
### by default groupby returns a groupby object which is an iterator and we need to use aggregation function to get the result
### this will group the dataframe by genre and return the mean of each column for each genre
### while using aggreation we need to make sure that we specify numberic only columns
### after dividing into groups it tries to calculate the mean of each column
print(return_value)
### this will return the mean of each column for each genre
### top3 by total earnin 
total_earnings = imdb.groupby('Genre').sum()['Gross'].sort_values(ascending=False).head(3)  
print(total_earnings)
### director by popularity

director_popularity = imdb.groupby('Director').mean(numeric_only=True)['No_of_Votes'].sort_values   
print(director_popularity)

{'Action': [2, 5, 8, 10, 13, 14, 16, 29, 30, 31, 39, 42, 44, 55, 57, 59, 60, 63, 68, 72, 106, 109, 129, 130, 134, 140, 142, 144, 152, 155, 160, 161, 166, 168, 171, 172, 177, 181, 194, 201, 202, 216, 217, 223, 224, 236, 241, 262, 275, 294, 308, 320, 325, 326, 331, 337, 339, 340, 343, 345, 348, 351, 353, 356, 357, 362, 368, 369, 375, 376, 390, 410, 431, 436, 473, 477, 479, 482, 488, 493, 496, 502, 507, 511, 532, 535, 540, 543, 564, 569, 570, 573, 577, 582, 583, 602, 605, 608, 615, 623, ...], 'Adventure': [21, 47, 93, 110, 114, 116, 118, 137, 178, 179, 191, 193, 209, 226, 231, 247, 267, 273, 281, 300, 301, 304, 306, 323, 329, 361, 366, 377, 402, 406, 415, 426, 458, 470, 497, 498, 506, 513, 514, 537, 549, 552, 553, 566, 576, 604, 609, 618, 638, 647, 675, 681, 686, 692, 711, 713, 739, 755, 781, 797, 798, 851, 873, 884, 912, 919, 947, 957, 964, 966, 984, 991], 'Animation': [23, 43, 46, 56, 58, 61, 66, 70, 101, 135, 146, 151, 158, 170, 197, 205, 211, 213, 219, 229, 230, 242, 245, 246, 270, 330, 332, 358, 367, 378, 386, 389, 394, 395, 399, 401, 405, 409, 469, 499, 510, 516, 518, 522, 578, 586, 592, 595, 596, 599, 633, 640, 643, 651, 665, 672, 694, 728, 740, 741, 744, 756, 758, 761, 771, 783, 796, 799, 822, 828, 843, 875, 891, 892, 902, 906, 920, 956, 971, 976, 986, 992], 'Biography': [7, 15, 18, 35, 38, 54, 102, 107, 131, 139, 147, 157, 159, 173, 176, 212, 215, 218, 228, 235, 243, 263, 276, 282, 290, 298, 317, 328, 338, 342, 346, 359, 360, 365, 372, 373, 385, 411, 416, 418, 424, 429, 484, 525, 536, 542, 545, 575, 579, 587, 600, 606, 614, 622, 632, 635, 644, 649, 650, 657, 671, 673, 684, 729, 748, 753, 757, 759, 766, 770, 779, 809, 810, 815, 820, 831, 849, 858, 877, 882, 897, 910, 915, 923, 940, 949, 952, 987], 'Comedy': [19, 26, 51, 52, 64, 78, 83, 95, 96, 112, 117, 120, 127, 128, 132, 153, 169, 183, 192, 204, 207, 208, 214, 221, 233, 238, 240, 250, 251, 252, 256, 261, 266, 277, 284, 311, 313, 316, 318, 322, 327, 374, 379, 381, 392, 396, 403, 413, 414, 417, 427, 435, 445, 446, 449, 455, 459, 460, 463, 464, 466, 471, 472, 475, 481, 490, 494, 500, 503, 509, 526, 528, 530, 531, 533, 538, 539, 541, 547, 557, 558, 562, 563, 565, 574, 591, 593, 594, 598, 613, 626, 630, 660, 662, 667, 679, 680, 683, 687, 701, ...], 'Crime': [1, 3, 4, 6, 22, 25, 27, 28, 33, 37, 41, 71, 77, 79, 86, 87, 103, 108, 111, 113, 123, 125, 133, 136, 162, 163, 164, 165, 180, 186, 187, 189, 198, 222, 232, 239, 255, 257, 287, 288, 299, 305, 335, 363, 364, 380, 384, 397, 437, 438, 441, 442, 444, 450, 451, 465, 474, 480, 485, 487, 505, 512, 519, 520, 523, 527, 546, 556, 560, 584, 597, 603, 607, 611, 621, 639, 653, 664, 669, 676, 695, 708, 723, 762, 763, 767, 775, 791, 795, 802, 811, 823, 827, 833, 885, 895, 921, 922, 926, 938, ...], 'Drama': [0, 9, 11, 17, 20, 24, 32, 34, 36, 40, 45, 50, 53, 62, 65, 67, 73, 74, 76, 80, 82, 84, 85, 88, 89, 90, 91, 92, 94, 97, 98, 99, 100, 104, 105, 121, 122, 124, 126, 138, 141, 143, 148, 149, 150, 154, 156, 167, 174, 175, 182, 184, 185, 188, 190, 195, 196, 199, 200, 203, 206, 210, 225, 227, 234, 237, 244, 248, 249, 253, 254, 258, 259, 260, 264, 265, 268, 269, 272, 274, 278, 279, 280, 283, 285, 286, 289, 291, 292, 293, 295, 296, 297, 302, 303, 307, 310, 312, 314, 315, ...], 'Family': [688, 698], 'Fantasy': [321, 568], 'Film-Noir': [309, 456, 712], 'Horror': [49, 75, 271, 419, 544, 707, 724, 844, 876, 932, 948], 'Mystery': [69, 81, 119, 145, 220, 393, 420, 714, 829, 899, 959, 961], 'Thriller': [700], 'Western': [12, 48, 115, 691]}
              Runtime  IMDB_Rating    No_of_Votes         Gross  Metascore
Genre
Action     129.046512     7.949419  420246.581395  1.897224e+08  73.419580
Adventure  134.111111     7.937500  313557.819444  1.319017e+08  78.437500
Animation   99.585366     7.930488  268032.073171  1.784326e+08  81.093333
Biography  136.022727     7.938636  272805.045455  9.404952e+07  76.240506
Comedy     112.129032     7.901290  178195.658065  1.010572e+08  78.720000
Crime      126.392523     8.016822  313398.271028  7.899656e+07  77.080460
Drama      124.737024     7.957439  212343.612457  1.225259e+08  79.701245
Family     107.500000     7.800000  275610.500000  2.195553e+08  79.000000
Fantasy     85.000000     8.000000   73111.000000  3.913633e+08        NaN
Film-Noir  104.000000     7.966667  122405.000000  4.197018e+07  95.666667
Horror     102.090909     7.909091  340232.363636  9.405902e+07  80.000000
Mystery    119.083333     7.975000  350250.333333  1.047014e+08  79.125000
Thriller   108.000000     7.800000   27733.000000  1.755074e+07  81.000000
Western    148.250000     8.350000  322416.250000  1.455538e+07  78.250000
Genre
Drama     3.540997e+10
Action    3.263226e+10
Comedy    1.566387e+10
Name: Gross, dtype: float64
<bound method Series.sort_values of Director
Aamir Khan             168895.0
Aaron Sorkin            89896.0
Abdellatif Kechiche    138741.0
Abhishek Chaubey        27175.0
Abhishek Kapoor         32628.0
                         ...
Zack Snyder            616837.5
Zaza Urushadze          40382.0
Zoya Akhtar             49906.5
Çagan Irmak             78925.0
Ömer Faruk Sorak        56960.0
Name: No_of_Votes, Length: 548, dtype: float64>

Some groupby attributes and methods are 
# GroupBy Attributes and Methods
# find total number of groups -> len
# find items in each group -> size
# first()/last() -> nth item
# get_group -> vs filtering
# groups
# describe
# sample
# nunique

In [ ]:
### merging and joining dataframes
##### concatenation is used to combine two dataframes along a particular axis, either rows or columns.
### depending on how we mention the columns we can concatenate along the rows or columns
### there are two axis 0 and 1
### axis 1 is for columns and axis 0 is for rows
### if the number of rows in one dataset is lesss as compared to the other dataset then the missing values will be filled with NaN
regs = pd.concat([imdb,delevires],axis=1)### this will concatenate the two dataframes along the columns

rows = pd.concat([imdb,delevires],axis=0)
### this will concatenate the two dataframes along the rows
print(rows)
### axis 0 stacking has two possibilities
### possibility one the number of columns in both dataframes is same then the rows will be stacked one below the other
### possibility two the number of columns in both dataframes is different then the missing values will be filled with NaN
### merging is used to combine two dataframes based on a common column or
### append and rows both do stacking 
### the differece is append can do stacking along rows or axis 0
### merge is similar to sql inner join a common columns is needed in both

                    Series_Title Released_Year  Runtime   Genre  IMDB_Rating  \
0       The Shawshank Redemption          1994    142.0   Drama          9.3
1                  The Godfather          1972    175.0   Crime          9.2
2                The Dark Knight          2008    152.0  Action          9.0
3         The Godfather: Part II          1974    202.0   Crime          9.0
4                   12 Angry Men          1957     96.0   Crime          9.0
...                          ...           ...      ...     ...          ...
179073                       NaN           NaN      NaN     NaN          NaN
179074                       NaN           NaN      NaN     NaN          NaN
179075                       NaN           NaN      NaN     NaN          NaN
179076                       NaN           NaN      NaN     NaN          NaN
179077                       NaN           NaN      NaN     NaN          NaN

                    Director           Star1  No_of_Votes        Gross  \
0             Frank Darabont     Tim Robbins    2343110.0   28341469.0
1       Francis Ford Coppola   Marlon Brando    1620367.0  134966411.0
2          Christopher Nolan  Christian Bale    2303232.0  534858444.0
3       Francis Ford Coppola       Al Pacino    1129952.0   57300000.0
4               Sidney Lumet     Henry Fonda     689845.0    4360000.0
...                      ...             ...          ...          ...
179073                   NaN             NaN          NaN          NaN
179074                   NaN             NaN          NaN          NaN
179075                   NaN             NaN          NaN          NaN
179076                   NaN             NaN          NaN          NaN
179077                   NaN             NaN          NaN          NaN

        Metascore  ...  bye_runs  legbye_runs noball_runs penalty_runs  \
0            80.0  ...       NaN          NaN         NaN          NaN
1           100.0  ...       NaN          NaN         NaN          NaN
2            84.0  ...       NaN          NaN         NaN          NaN
3            90.0  ...       NaN          NaN         NaN          NaN
4            96.0  ...       NaN          NaN         NaN          NaN
...           ...  ...       ...          ...         ...          ...
179073        NaN  ...       0.0          0.0         0.0          0.0
179074        NaN  ...       0.0          0.0         0.0          0.0
179075        NaN  ...       0.0          0.0         0.0          0.0
179076        NaN  ...       0.0          0.0         0.0          0.0
179077        NaN  ...       0.0          0.0         0.0          0.0

        batsman_runs  extra_runs total_runs player_dismissed dismissal_kind  \
0                NaN         NaN        NaN              NaN            NaN
1                NaN         NaN        NaN              NaN            NaN
2                NaN         NaN        NaN              NaN            NaN
3                NaN         NaN        NaN              NaN            NaN
4                NaN         NaN        NaN              NaN            NaN
...              ...         ...        ...              ...            ...
179073           1.0         0.0        1.0              NaN            NaN
179074           2.0         0.0        2.0              NaN            NaN
179075           1.0         0.0        1.0        SR Watson        run out
179076           2.0         0.0        2.0              NaN            NaN
179077           0.0         0.0        0.0        SN Thakur            lbw

          fielder
0             NaN
1             NaN
2             NaN
3             NaN
4             NaN
...           ...
179073        NaN
179074        NaN
179075  KH Pandya
179076        NaN
179077        NaN

[180078 rows x 31 columns]

multiindex in pandas
What is an index?
- an index is a label , the whole idea of using pandas is becuase we have labels
- in numpy we only have positioned indexes
- multindex allows us to have multiple levels of index on Dataframesrows or columns
Can we have multplie indexes in series
- Yes a series can also have multindex it is series because it only has 1 d data
What special feature or advantage does multindex give us
- With multiindex we can access the data using two level of indexes

In [ ]:
### creating a multiindex dataframe
import pandas as pd

data = {
    "City": ["Toronto", "Toronto", "Thunder Bay", "Thunder Bay"],
    "Year": [2024, 2025, 2024, 2025],
    "Sales": [100, 150, 80, 120]
}

df = pd.DataFrame(data)

df = df.set_index(["City", "Year"])

print(df)
### accessing the multiindex dataframe using index we use loc
df.loc[("Toronto", 2024)]
### if we have multiple indexes then we dont need to specify all of them we can mention the index we want to use
df.loc["Thunder Bay"]

                  Sales
City        Year
Toronto     2024    100
            2025    150
Thunder Bay 2024     80
            2025    120

      Sales
Year
2024     80
2025    120

setindex vs multi index
Setindex functions
-set_index() is a DataFrame method used to assign one or more existing columns as the row index.
- its like converting column to index   
- MultiIndex is an index structure that supports multiple levels.

Vectorized string
A vectorized string in Python usually refers to performing string operations on an entire Series of strings in Pandas at once, without writing an explicit for loop.
import pandas as pd

names = pd.Series(["jeevan", "john", "alice"])

# Some common vectorized string methods
Common vectorized string methods
Method	Purpose	Example
.str.upper()	Convert to uppercase	"hello" → "HELLO"
.str.lower()	Convert to lowercase	"HELLO" → "hello"
.str.strip()	Remove surrounding whitespace	" hi " → "hi"
.str.contains()	Check for a substring	"hello" → True
.str.replace()	Replace text	"cat" → "dog"
.str.len()	Find string length	"hello" → 5
.str.split()	Split strings	"John Doe" → ["John", "Doe"]

In [ ]:
import pandas as pd

names = pd.Series(["jeevan", "john", "alice"])

# Vectorized string operation
names.str.upper()